apiVersion: v1
kind: Pod
metadata:
 name: monitoring-service
 labels:
  app: monitoring-service
spec:
 containers:
 - name: monitoring-service
   image: sandeshdhotre/monitoringapp:latest
   ports:
    - name: monitoringport
      containerPort: 9010
